[project]
name = "chapter9-openai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ddgs>=9.10.0",
    "openai-agents[litellm]>=0.7.0",
]
